all: insertion selection bubble merge problem_sets

problem_sets: plurality

insertion: insertion_sort.c
	gcc -o insertion insertion_sort.c

selection: selection_sort.c
	gcc -o selection selection_sort.c

bubble: bubble_sort.c
	gcc -o bubble bubble_sort.c

merge: merge_sort.c
	gcc -o merge merge_sort.c

plurality: plurality.c
	gcc -o plurality plurality.c