all: hello mario cash credit tifc

hello: hello.c
	gcc -o hello hello.c

mario: mario.c
	gcc -o mario mario.c

cash: cash.c
	gcc -o cash cash.c

credit: credit.c
	gcc -o credit credit.c

tifc: take_input_from_cli.c
	gcc -o take_input_from_cli take_input_from_cli.c

clean:
	rm hello mario cash